## Libraries

In [15]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from scipy.optimize import curve_fit

## 1. Linear Fit

### i. Dataset

In [16]:
np.random.seed(3)

X = np.arange(-30, 30).reshape(-1, 1)
y = 3 * X - 2
y = y + np.random.uniform(-20, 20, size=X.shape)

In [17]:
plt.scatter(X, y)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=8, shuffle=False)

In [19]:
X_train.flatten(), y_train.flatten(), y_train.shape

(array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
        -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
         -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
          9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21]),
 array([-89.9680839 , -80.6740871 , -94.36381044, -82.56689579,
        -64.28212183, -61.14827644, -88.97658758, -82.71028487,
        -85.94131187, -67.36760625, -80.80495156, -60.72667102,
        -50.0342381 , -61.86050869, -42.94980392, -43.3654873 ,
        -63.0407247 , -38.64583648, -47.62990212, -38.39595212,
        -40.65899673, -21.27448327, -28.38185129, -36.72529046,
        -18.21403928,  -5.78740942, -21.7454587 , -22.12168464,
        -12.4811497 ,  12.45534599,  17.0398169 ,   7.89534704,
         20.11336434,  20.83003485,   5.11976165,  -3.31131965,
         22.1364361 ,  21.3136305 ,  16.46259052,  14.00218019,
         24.26079666,  29.75760995,  24.76942313,  28.67171097,
  

In [20]:
X_test.flatten(), y_test.flatten(), y_test.shape

(array([22, 23, 24, 25, 26, 27, 28, 29]),
 array([64.56140239, 50.48917475, 69.34342129, 67.4870485 , 84.30746487,
        88.86984892, 89.64371687, 92.56721655]),
 (8, 1))

### ii. Model

In [21]:
m = LinearRegression()
m.fit(X_train, y_train)

LinearRegression()

In [22]:
print("slope:", m.coef_)
print("intercept:", m.intercept_)

slope: [[2.96799936]]
intercept: [-3.84078726]


### iii. Predict

In [23]:
y_pred = m.predict(X_test)
y_pred

array([[61.45519866],
       [64.42319802],
       [67.39119738],
       [70.35919674],
       [73.3271961 ],
       [76.29519546],
       [79.26319482],
       [82.23119418]])

In [24]:
# Fitting on whole data
plt.plot(X, y, 'o')
plt.plot(X, m.coef_ * X + m.intercept_)

### iv. Evalute

In [25]:
mean_absolute_error(y_test, y_pred) ,mean_squared_error(y_test, y_pred), r2_score(y_test, y_pred)

(8.26700822627712, 88.64284103244196, 0.5550136423436166)